### ISSUE TITLE
不能转发「贴纸」

### ISSUE THREAD

**Issue by seiuneko** [jqqqqqqqqqq/coolq-telegram-bot#13]
如题 

以下是日志

```
[CTBot] JSON Config file support [Enable]
telegram.vendor.ptb_urllib3.urllib3.connectionpool: WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',))': /bot**********************************************************/getUpdates
telegram.vendor.ptb_urllib3.urllib3.connectionpool: WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',))': /bot**********************************************************/getUpdates
telegram.vendor.ptb_urllib3.urllib3.connectionpool: WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',))': /bot**********************************************************/getUpdates
telegram.vendor.ptb_urllib3.urllib3.connectionpool: WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',))': /bot**********************************************************/getUpdates
telegram.vendor.ptb_urllib3.urllib3.connectionpool: WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',))': /bot**********************************************************/getUpdates
Traceback (most recent call last):
  File "/home/user/coolq-telegram-bot/cqsdk.py", line 291, in handle
    listener.handler(message)):
  File "/home/user/coolq-telegram-bot/plugins/_003_debug_all_message.py", line 107, in test
    qq_group_id = int(message.group)
AttributeError: 'RcvGroupMemberList' object has no attribute 'group'
telegram.vendor.ptb_urllib3.urllib3.connectionpool: WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',))': /bot**********************************************************/getUpdates
telegram.vendor.ptb_urllib3.urllib3.connectionpool: WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',))': /bot**********************************************************/getUpdates
telegram.vendor.ptb_urllib3.urllib3.connectionpool: WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',))': /bot**********************************************************/getUpdates
telegram.vendor.ptb_urllib3.urllib3.connectionpool: WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',))': /bot**********************************************************/getUpdates
telegram.vendor.ptb_urllib3.urllib3.connectionpool: WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',))': /bot**********************************************************/getUpdates
telegram.vendor.ptb_urllib3.urllib3.connectionpool: WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',))': /bot**********************************************************/getUpdates
```

谢谢～

那个 顺便问下 QQ 群怎么发贴纸喵？
还有 上面的

```
telegram.vendor.ptb_urllib3.urllib3.connectionpool: WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',))': /bot**********************************************************/getUpdates
```

很烦 这是什么原因呢？

再次感谢你对这个项目的贡献

**Comment by jqqqqqqqqqq** [comment]
看起来是你的telegram 根本没连上服务器？检查你的代理设置

**Comment by jqqqqqqqqqq** [comment]
ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',))

仔细读一下

**Comment by seiuneko** [comment]
代理应该是没问题的 
可以正常从 tg 转发图片到 QQ  
然后 贴纸只有

>[🎗 sticker]

**Comment by jqqqqqqqqqq** [comment]
你是 Air 吗？
你用的是 master 还是 dev？

**Comment by seiuneko** [comment]
Pro
master
![qq 20171211162635](https://user-images.githubusercontent.com/25706824/33821899-84bfbeb8-de90-11e7-9f5a-9ecedd52ada7.png)


\# 发现不支持 GIF 的说 最后一个是 GIF

**Comment by jqqqqqqqqqq** [comment]
你的截图没传上来

GIF 暂时没支持，因为 telegram 的 gif 其实是 mp4

**Comment by seiuneko** [comment]
那个 请问还需要提供什么信息呢？

**Comment by jqqqqqqqqqq** [comment]
你能发一下你的配置文件么，token 什么删掉就行

**Comment by xyf1219** [comment]
{
    "TOKEN": "444696256:AAGxoT-Wdm0J0ncBu-0BYwU0R70A6vrLbTU",
    "QQ_BOT_ID": 2653575061,
    "FORWARD_LIST": [
        {
            "QQ": 665465384,
            "TG": -1001197463640,
            "Drive_mode": false,
            "Pic_link": false
        }
    ],
    "SERVER_PIC_URL": "http://example.com:8080/image/",
    "CQ_ROOT": "/home/user/coolq/",
    "CQ_PORT": 11235,
    "JQ_MODE": true
}

哦对了 使用的是

**Comment by seiuneko** [comment]
```
{
    "TOKEN": "***********************************",
    "QQ_BOT_ID": *********,
    "FORWARD_LIST": [
        {
            "QQ": ************,
            "TG": -***************,
            "Drive_mode": false,
            "Pic_link": false
        }
    ],
    "SERVER_PIC_URL": "http://example.com:8080/image/",
    "CQ_ROOT": "/home/user/coolq/",
    "CQ_PORT": 11235,
    "JQ_MODE": true
}
```

哦对了 使用的是
[Z4HD/coolq-telegram-bot-docker: 使用 Docker 容器化的 QQ 和 Telegram 的消息互转机器人。Source: jqqqqqqqqqq/coolq-telegram-bot](https://github.com/Z4HD/coolq-telegram-bot-docker)

**Comment by jqqqqqqqqqq** [comment]
json 版我没测试过。。。
可能是你发现了一个 bug？

**Comment by seiuneko** [comment]
还是不行……

**Comment by jqqqqqqqqqq** [comment]
Python 版 config可以吗？

**Comment by seiuneko** [comment]
现在使用的就是 Python 版 config

```
# -*- coding: utf-8 -*-
TOKEN = '*********************************'
QQ_BOT_ID = **************
FORWARD_LIST = [
    {
        'QQ': ***********,
        'TG': -************,
        'Drive_mode': False,
        'Pic_link': False
    },
]
SERVER_PIC_URL = 'http://example.com:8080/image/'
CQ_ROOT = '/home/user/coolq/'
CQ_PORT = 11235
JQ_MODE = True  # if use Coolq Pro, set as True, otherwise False
```

**Comment by jqqqqqqqqqq** [comment]
你的True的t大写了么

**Comment by jqqqqqqqqqq** [comment]
因为我用Python 版无法复现这个问题…

**Comment by jqqqqqqqqqq** [comment]
我看看还有什么问题

**Comment by jqqqqqqqqqq** [comment]
你把pic_link那个改成true

**Comment by seiuneko** [comment]
哇真的是这个原因 谢谢

**Comment by jqqqqqqqqqq** [comment]
我描述写的不到位，抱歉，下个版本会修改一下

**Comment by seiuneko** [comment]
没事的 不过为什么会这样呢？

**Comment by jqqqqqqqqqq** [comment]
可能是逻辑写的有点不太合适，按理说JQ_MODE应该完全不会用到那一项

**Comment by seiuneko** [comment]
好吧 
哦对了 怎么实现「QQ 群可以通过指令向 Telegram 群发送 Sticker」
看文档里没写到……

**Comment by jqqqqqqqqqq** [comment]
那个功能因为没什么卵用准备移除了

**Comment by seiuneko** [comment]
好的

**Comment by Z4HD** [comment]
`dev`分支中的`sticker_from_telegram()`相关逻辑将于近期被修改。（但不是现在）

**Comment by jqqqqqqqqqq** [comment]
逻辑已修改
