### ISSUE TITLE
执行pip3 install -r requirements.txt报错

### ISSUE THREAD

**Issue by hsdchenliyang** [jqqqqqqqqqq/coolq-telegram-bot#9]
之前有一次安装是可以的 但被我pip3 uninstall -r requirements.txt卸载了 然后想再安装就出现错误了  pip3重装了也不行  谁能告诉我大概是什么问题……

Collecting APScheduler==3.3.1 (from -r requirements.txt (line 1))
  Downloading APScheduler-3.3.1-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 3.3kB/s 
Collecting beautifulsoup4==4.6.0 (from -r requirements.txt (line 2))
  Downloading beautifulsoup4-4.6.0-py3-none-any.whl (86kB)
    100% |████████████████████████████████| 92kB 6.9kB/s 
Collecting certifi==2017.7.27.1 (from -r requirements.txt (line 3))
  Downloading certifi-2017.7.27.1-py2.py3-none-any.whl (349kB)
    67% |█████████████████████▋          | 235kB 3.8kB/s eta 0:00:31Exception:
Traceback (most recent call last):
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/response.py", line 226, in _error_catcher
    yield
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/response.py", line 301, in read
    data = self._fp.read(amt)
  File "/usr/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl/cachecontrol/filewrapper.py", line 49, in read
    data = self.__fp.read(amt)
  File "/usr/lib/python3.5/http/client.py", line 448, in read
    n = self.readinto(b)
  File "/usr/lib/python3.5/http/client.py", line 488, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 317, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 577, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 810, in unpack_url
    hashes=hashes
  File "/usr/lib/python3/dist-packages/pip/download.py", line 649, in unpack_http_url
    hashes)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 871, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 595, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/usr/lib/python3/dist-packages/pip/utils/hashes.py", line 46, in check_against_chunks
    for chunk in chunks:
  File "/usr/lib/python3/dist-packages/pip/download.py", line 563, in written_chunks
    for chunk in chunks:
  File "/usr/lib/python3/dist-packages/pip/utils/ui.py", line 139, in iter
    for x in it:
  File "/usr/lib/python3/dist-packages/pip/download.py", line 552, in resp_read
    decode_content=False):
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/response.py", line 344, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/response.py", line 311, in read
    flush_decoder = True
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/response.py", line 231, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out.

**Comment by jqqqqqqqqqq** [comment]
看最后一行，应该是你到pypi.python.org的连接性出现了问题，你需要解决这个问题

**Comment by hsdchenliyang** [comment]
谢谢哦

**Comment by hsdchenliyang** [comment]
不好意思 再问一下 之前也出现以下错误 但是安装了requirement.txt 就好了 但是这一次安装了requirement.txt也说没有telegram模块？

Traceback (most recent call last):
  File "daemon.py", line 7, in <module>
    from telegram.ext import Updater, CommandHandler, InlineQueryHandler,\
ImportError: No module named 'telegram'

**Comment by hsdchenliyang** [comment]
原因应该是国外官方pypi被墙  我临时用了镜像  清华：https://pypi.tuna.tsinghua.edu.cn/simple
命令sudo pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt  就可以了 记得加sudo

**Comment by jqqqqqqqqqq** [comment]
解决了就好
